spring:
 datasource:
   url: jdbc:mysql:///stu
   username: root
   password: 123
   driver-class-name: com.mysql.jdbc.Driver


dubbo:
  application:
    name: stu_service
  registry:
    address: zookeeper://192.168.180.128:2181
